// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAfQOsVb9UNN-S8pKxJef7YwEtQF_r9jk',
    appId: '1:1075398568719:web:e6cb12736f0ad9431bec7a',
    messagingSenderId: '1075398568719',
    projectId: 'florascan-d4001',
    authDomain: 'florascan-d4001.firebaseapp.com',
    storageBucket: 'florascan-d4001.firebasestorage.app',
    measurementId: 'G-VFV7464S8M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvIhmWLozeCp0Mg4ufcnBrD2frXKGGnbk',
    appId: '1:1075398568719:android:cb68ea2ba4d2e9f71bec7a',
    messagingSenderId: '1075398568719',
    projectId: 'florascan-d4001',
    storageBucket: 'florascan-d4001.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8kSqSObnE6ilih2fFOugarlxuzo6z6l8',
    appId: '1:1075398568719:ios:44f40abf44bb11871bec7a',
    messagingSenderId: '1075398568719',
    projectId: 'florascan-d4001',
    storageBucket: 'florascan-d4001.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8kSqSObnE6ilih2fFOugarlxuzo6z6l8',
    appId: '1:1075398568719:ios:44f40abf44bb11871bec7a',
    messagingSenderId: '1075398568719',
    projectId: 'florascan-d4001',
    storageBucket: 'florascan-d4001.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAfQOsVb9UNN-S8pKxJef7YwEtQF_r9jk',
    appId: '1:1075398568719:web:b572f3e7a01309d81bec7a',
    messagingSenderId: '1075398568719',
    projectId: 'florascan-d4001',
    authDomain: 'florascan-d4001.firebaseapp.com',
    storageBucket: 'florascan-d4001.firebasestorage.app',
    measurementId: 'G-YHE398YVDG',
  );
}
